kind: Service
apiVersion: v1
metadata:
  #Service name
  name: node-app
spec:
  selector:
    app: booking-online-clinic-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer